name: Teste

on:
  push:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Criar arquivo
        run: echo "isso foi criado no pipeline" > arquivo.txt

      - name: Mostrar arquivo
        run: cat arquivo.txt

      - name: Upload do arquivo
        uses: actions/upload-artifact@v4
        with:
          name: meu-arquivo
          path: arquivo.txt