name: Teste

on:
  push:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
  - name: Mostrar mensagem
    run: echo "rodando pipeline"

  - name: Mostrar arquivos
    run: ls -la

  - name: Mostrar sistema
    run: uname -a